name: Deploy to Edgio

on:
  workflow_dispatch:

env:
  REACT_APP_BRXM_ENDPOINT: https://layer0-docs-bloomreach-layer0-example-saas-default.layer0-limelight.link/api
  BRXM_ENDPOINT: trial-tnk8sgqr.bloomreach.io
  REACT_APP_GRAPHQL_SERVICE_URL: https://layer0-docs-bloomreach-layer0-example-saas-default.layer0-limelight.link/graphql
  GRAPHQL_SERVICE_URL: graphql.trial-tnk8sgqr.bloomreach.io

jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run:|
          npm ci
          CI=false npm run build
          npm run deploy -- --token=$EDGIO_DEPLOY_TOKEN
        env:
          EDGIO_DEPLOY_TOKEN: ${{secrets.EDGIO_DEPLOY_TOKEN}}
