name: Deploy Examples (dev-only)

on:
  pull_request:
  workflow_dispatch:

# In case you push new commit into the MR / the previous runs will automatically stop
concurrency:
  group: dev-examples-${{ github.ref }}
  cancel-in-progress: true

env:
  # Node version for all the jobs
  NODE_VERSION: 16

  # Set env var based on branch name
  GIT_REF: ${{ github.ref }}
  EDGIO_ENV: ${{ github.ref == 'refs/heads/main' && 'live' || 'test' }}
  EDGIO_TEAM: 'layer0-docs'
  EDGIO_SITE: 'edgio-examples'
  EDGIO_DEPLOY_TOKEN: ${{secrets.EDGIO_EXAMPLES_DEPLOY_TOKEN}}
  OPTIONAL_API_URL: --api-url=https://app.layer0.co

jobs:
  prepare-env:
    name: 'Prepare env for examples'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setMatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }} # NODE_VERSION
          registry-url: https://registry.npmjs.org/
      - name: 'Cache node modules'
        uses: actions/cache@v3
        env:
          cache-name: cache-packages-node-modules-node16-v1
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json', 'packages/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: 'Generate preid of this build'
        id: setPreid
        run: echo -e "preid=next-$(date +'%s')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - run: npm ci

      - name: 'Load list of examples'
        id: setMatrix
        run: |
          echo -e "matrix=$(node scripts/helpers/printExamples.js)" >> $GITHUB_OUTPUT

  examples:
    name: 'Examples'
    needs: prepare-env
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        example: ${{ fromJson( needs.prepare-env.outputs.matrix ) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }} # NODE_VERSION
          registry-url: https://registry.npmjs.org/

      - name: 'Cache node modules'
        uses: actions/cache@v3
        env:
          cache-name: cache-examples-node-modules-${{ matrix.example }}-node16-v2
        with:
          path: |
            examples/${{ matrix.example }}/node_modules
            /opt/hostedtoolcache/node/14.20.1/x64/lib/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('examples/{0}/package-lock.json', matrix.test), 'packages/*/package-lock.json') }}

      # Install dependencies for this example
      - name: 'Install dependencies'
        run: |
          npm i -g @edgio/cli
          npm i --prefix ./examples/${{ matrix.example }}

      - name: 'Disable analytics'
        run: edgio config set-analytics false

      - name: 'Prepare environments for the example'
        run: |
          common_args="--site=$EDGIO_SITE --team=$EDGIO_TEAM --token=$EDGIO_DEPLOY_TOKEN $OPTIONAL_API_URL"
          echo "edgio env list $common_args"
          output=$(eval "edgio env list $common_args")
          envs_line=$(echo "$output" | grep "Environments:")  # get the line that contains the list of environments
          envs=${envs_line#*: }  # remove the "Environments: " prefix from the line
          IFS=$'\n' read -rd '' -a envs_array <<< "$envs"  # split the string by newline and store the resulting array in envs_array
          if [[ " ${envs_array[@]} " =~ " ${ENV_NAME} " ]]; then
            # environment exists in the list; skip it
            echo "Environment ${ENV_NAME} already exists in the list of environments and is being skipped."
          else
            # environment doesn't exist in the list; add it
            edgio env add $common_args --environment=$ENV_NAME
          fi
        env:
          ENV_NAME: ${{ matrix.example }}-${{ env.EDGIO_ENV }}

      # - name: 'Deploy examples'
      #   run: npm run ci:deploy --prefix ./integration-tests/${{ matrix.example }}
