name: Update Edgio Examples
on:
  workflow_dispatch:

concurrency:
  group: update-examples-${{ github.ref }}
  cancel-in-progress: true

env:
  # Node version for all the jobs
  NODE_VERSION: 16
  BRANCH_NAME: update-edgio-${{ github.run_number }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setMatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }} # NODE_VERSION
          registry-url: https://registry.npmjs.org/
      - name: Install Node.js modules
        run: npm ci
      - name: Create branch and push to origin
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}
      - name: Get matrix of examples
        id: setMatrix
        run: echo -e "matrix=$(node scripts/helpers/printExamples.js)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-examples:
    name: Update Examples
    needs: prepare
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        example: ${{ fromJson( needs.prepare.outputs.matrix ) }}
    env:
      EXAMPLE_DIR: examples/${{ matrix.example }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }} # NODE_VERSION
          registry-url: https://registry.npmjs.org/
      - name: Install Node.js modules
        run: |
          npm i -g @edgio/cli
          npm ci
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-examples-node-modules-${{ matrix.example }}-node16-v2
        with:
          path: |
            examples/${{ matrix.example }}/node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('examples/{0}/package-lock.json', matrix.test), 'packages/*/package-lock.json') }}

      - name: Update Examples
        run: npm run update-examples ${{ env.EXAMPLE_DIR }}

      - name: Check if there are modified files
        id: status
        run: |
          # Check if the git status is clean
          if [ -z "$(git status --porcelain)" ]; then
            echo "No modified files"
            # Set a variable to indicate that there are no modified files
            echo "NO_MODIFIED_FILES=true" >> $GITHUB_OUTPUT
          else
            echo "Modified files"
            # Set a variable to indicate that there are modified files
            echo "NO_MODIFIED_FILES=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit changes
        if: steps.status.outputs.NO_MODIFIED_FILES == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin ${{ env.BRANCH_NAME }}
          git add .
          git commit -am "Update ${{ matrix.example }}"
          git push origin ${{ env.BRANCH_NAME }}

  create-pr:
    name: Create PR
    needs: update-examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
      - name: Check for file changes
        id: status
        run: |
          git pull
          HAS_CHANGED_FILES=$(git diff --name-only origin/main | grep -q . && echo true || echo false)
          echo "HAS_CHANGED_FILES=$HAS_CHANGED_FILES" >> $GITHUB_OUTPUT
      - name: Create PR
        if: steps.status.outputs.HAS_CHANGED_FILES == 'true'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.repository.default_branch }}
          pr_title: '[BOT] Update Edgio Examples'
          pr_reviewer: ${{ github.repository_owner }}
          pr_assignee: ${{ github.repository_owner }}
      - name: Delete branch
        if: steps.status.outputs.HAS_CHANGED_FILES == 'false'
        run: |
          git push origin --delete ${{ env.BRANCH_NAME }}
