import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { event } from 'nextjs-google-analytics';
import cookieCutter from 'cookie-cutter';
import { useEffect, useState } from 'react';

export default function Home() {
  function trackEvent(e) {
    event('button-clicked', {
      category: 'Edgio A/B Environment',
      label: destination,
    });
    setEventData(window.dataLayer.pop());
  }

  const [destination, setDestination] = useState('');
  const [eventData, setEventData] = useState();
  useEffect(() => setDestination(cookieCutter.get('edgio_destination')), []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          This example application has an A/B test splittng traffic 50/50 to
          either `default` or `split_test` environments configured in the Edgio
          Developer Console.
        </p>

        <p>
          Your experience is determined by a `edgio_destination` cookie which
          defines the environment that responded to this request. You will
          remain on this experience until your browser session expires.
        </p>
        <p>
          Your <code className={styles.code}>edgio_destination</code> cookie is{' '}
          <code className={styles.code}>{destination}</code>.
        </p>
        <p>
          <button onClick={trackEvent}>Click here</button> to track this event.
        </p>

        {eventData && (
          <p>
            <div>
              The analytic event contained the following details:
              <pre className={styles.code}>
                {JSON.stringify(eventData, null, 2)}
              </pre>
            </div>
          </p>
        )}
      </main>
    </div>
  );
}
